package com.emc.settlement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SettlementRunException implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String execStep;

   private java.lang.String message;

   public SettlementRunException()
   {
   }

   public java.lang.String getExecStep()
   {
      return this.execStep;
   }

   public void setExecStep(java.lang.String execStep)
   {
      this.execStep = execStep;
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public SettlementRunException(java.lang.String execStep,
         java.lang.String message)
   {
      this.execStep = execStep;
      this.message = message;
   }

}