package com.emc.settlement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SQLException implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public SQLException()
   {
   }

}